// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxQb_Da6URYwRl8Gn24YNOZ6dpwhnItQE',
    appId: '1:136670084214:web:f74b78b4d87520615ff357',
    messagingSenderId: '136670084214',
    projectId: 'pokemon-fiap',
    authDomain: 'pokemon-fiap.firebaseapp.com',
    storageBucket: 'pokemon-fiap.appspot.com',
    measurementId: 'G-C0FPXX51VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdNY1sU806s8OTnRjeLlHxbX8QEawhjPU',
    appId: '1:136670084214:android:ef08c49632ead72e5ff357',
    messagingSenderId: '136670084214',
    projectId: 'pokemon-fiap',
    storageBucket: 'pokemon-fiap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC62WcdKKNq_Z6dmjmxLq1yhI1fpSbt9Xo',
    appId: '1:136670084214:ios:cd553069f1e5ff445ff357',
    messagingSenderId: '136670084214',
    projectId: 'pokemon-fiap',
    storageBucket: 'pokemon-fiap.appspot.com',
    iosClientId: '136670084214-9i9p8d2jmmdnom5hpmlor8sqpio9srvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokemon',
  );
}
